[build]
  functions = "handler"
  command = "npm run download && npm run build"
  publish = "public/"

[watch]
  functions = "handler"
  command = "npm run download && npm run build"
  publish = "public/"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["cache/data.json"]
