#!/bin/sh
#
# Copyright (c) 2015, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

set -e

mkdir -p lib/public

cp src/public/*.{ico,html} lib/public/

browserify -t babelify --outfile lib/public/swapi.js src/public/swapi.js

browserify \
  --standalone Schema \
  -t babelify \
  --outfile lib/public/schema.js \
  src/public/schema-proxy.js
