#!/bin/bash

set -e

if [ ! -s src/api/cachedData/cache.json ]; then
  echo 'Downloading cache...'
  babel-node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.json
  echo 'Cached!'
fi
