#!/bin/bash

# not used any more

set -e

if [ ! -s src/api/cachedData/cache.js ]; then
  echo 'Downloading cache...'
  babel-node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.js
  echo 'Cached!'
fi
